
version: '3'
services:
  db:
    restart: always
	  privileged: true
    image: mysql:8.0
    container_name: mysqlServer33106
    volumes:
      - ./db:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "12345678"
	ports:
      - 33106:3306
    network_mode: "bridge"
 
