name: my-actions
on: [push]

jobs:
  my-helloworld-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the program
        run: python chatbot.py
        
      - name: View a file
        run:
          echo 'Viewing the file:'
          cat requirements.txt
